name: GitHub - Label PRs
on:
  - pull_request_target

permissions:
  contents: read

jobs:
  triages:
    permissions:
      # for actions/labeler to determine modified files
      contents: read
      # for actions/labeler to add labels to PRs
      pull-requests: write
    runs-on: ubuntu-20.04
    steps:
      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          write-output '${{ secrets.GITHUB_TOKEN }}'
